[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "eight talent outer pond shed next century spot vacant sand near still around hint cheap jungle gather traffic polar surge rack admit sentence eagle"
